# Generated by Django 3.1.3 on 2022-04-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_answer_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='auth',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='auth',
            new_name='author',
        ),
    ]
